### ISSUE TITLE
Unable to build cordova

### ISSUE THREAD

**Issue by wsideveloper** [orchoban/react.cordova#6]
Two issues encountered:
1) "reco build" unable to build cordova. But "reco cordova build" works. 
2) "reco build" gives error when building cordova for iOS.

=============================

C:\Users\See Lin\www\reco\ttt>reco build

start build react

react-js@0.1.0 build C:\Users\See Lin\www\reco\ttt\react-js
react-scripts build

Creating an optimized production build...
Compiled with warnings.
...
...
The build folder is ready to be deployed.

Find out more about deployment here:

  https://bit.ly/CRA-deploy

> reco start to build cordova
> 
> child_process.js:210
>     throw new ERR_INVALID_ARG_VALUE('args', arguments[pos]);

 

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'args' is invalid. Received { cwd: 'cordova' }
    at Object.execFile (child_process.js:210:11)
    at Proxy.exec (child_process.js:152:18)
    at Object.reco.state.callBack_replaceWwwRootDir (C:\Users\See Lin\AppData\Roaming\npm\node_modules\react.cordova\bin\cli.js:121:46)
    at C:\Users\See Lin\AppData\Roaming\npm\node_modules\react.cordova\bin\cli.js:745:36
    at cb (C:\Users\See Lin\AppData\Roaming\npm\node_modules\react.cordova\node_modules\ncp\lib\ncp.js:255:37)
    at WriteStream.<anonymous> (C:\Users\See Lin\AppData\Roaming\npm\node_modules\react.cordova\node_modules\ncp\lib\ncp.js:133:14)
    at Object.onceWrapper (events.js:286:20)
    at WriteStream.emit (events.js:203:15)
    at WriteStream.EventEmitter.emit (domain.js:448:20)
    at finishMaybe (_stream_writable.js:646:14)

C:\Users\See Lin\www\reco\ttt>reco cordova build
Checking Java JDK and Android SDK versions

ANDROID_SDK_ROOT=C:\Tools\Android-sdk (recommended setting)
ANDROID_HOME=C:\Tools\Android-sdk (DEPRECATED)
...
....

BUILD SUCCESSFUL in 12s
42 actionable tasks: 2 executed, 40 up-to-date

Built the following apk(s):
        C:\Users\See Lin\www\reco\ttt\cordova\platforms\android\app\build\outputs\apk\debug\app-debug.apk

> **reco-cli-cordova ERROR : Error: Command failed: cordova build
> CordovaError: Promise rejected with non-error: 'xcodebuild was not found. Please install version 9.0.0 or greater from App Store'
>     at cli.catch.err (C:\Users\See Lin\AppData\Roaming\npm\node_modules\cordova\bin\cordova:29:15)
>     at process._tickCallback (internal/process/next_tick.js:68:7)**
>

**Comment by orchoban** [comment]
Hello @wsideveloper .

About the first problem.
I fixed the error and it will no longer appear in version 1.7.5
run `npm i -g react.cordova@latest`

For the second issue, you must run on mac to build for iPhone installation file.ipa.
You can give a command like `reco build android` and then there will be no attempt to produce a version for IOS

**Comment by wsideveloper** [comment]
Hi

Noted on the iOS build. Unfortunately I still get the same reco build error
despite updated to 1.7.6. I can live with reco cordova build for now.

C:\Users\See Lin\www\reco\ttt>npm list -g --depth=0
C:\Users\See Lin\AppData\Roaming\npm
+-- @angular/cli@8.3.17
+-- @vue/cli@4.0.5
+-- @vue/cli-init@4.0.5
+-- cordova@9.0.0
+-- create-react-app@3.2.0
+-- UNMET PEER DEPENDENCY react@>=15
+-- react-router-dom@5.1.2
+-- react.cordova@1.7.6
`-- typescript@3.7.2

npm ERR! peer dep missing: react@>=15, required by react-router-dom@5.1.2
npm ERR! peer dep missing: react@>=15, required by react-router@5.1.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by
mini-create-react-context@0.3.2

**Comment by orchoban** [comment]
Please try again:
`npm install -g react.cordova@latest`
  Please update if this is resolved

**Comment by orchoban** [comment]
The new version simulator works differently.  
You need to run: `reco i cordova_script` Then coordinate the code of the `src/inex.js` file to the following code:
https://github.com/orchoban/react.cordova/blob/master/templates/empty/index.js
